server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: /annunciator
    error:
        include-stacktrace: never

spring:
    application:
        name: annunciator
    config:
        import: optional:file:.env[.properties]
    mail:
        host: ${EMAIL_HOST:sandbox.smtp.mailtrap.io}
        port: ${EMAIL_PORT:2525}
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: ${EMAIL_SMTP_AUTH:true}
                    starttls:
                        enable: ${EMAIL_SMTP_STARTTLS_ENABLE:true}

app:
    redis:
        server: ${REDIS_SERVER:redis://localhost:6379}
        queue: ${REDIS_QUEUE:annunciator:email:sending-pending}