services:
    redis-server:
        image: redis:7.2.4-alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ${ANNUNCIATOR_VOLUME}:/data
        command: --save 60 1 --loglevel warning

